### ISSUE TITLE
Improve date stamp readability

### ISSUE THREAD

**Issue by zovits** [zovits/DashboardPageTest#1]
`GMT-0700 (Pacific Daylight Time)` is too verbose, try just abbreviated zone like `(PST)`.

**Comment by LorenzoZemp** [comment]
Hey I'll do it, could you assign this to me?

**Comment by zovits** [comment]
Sorry, this is not for the public. This is an unlicensed personal project, I just needed the repo to be public in order to use GitHub Pages. I appreciate the offer, and I hope you direct this energy towards others!
